export const initialSchedule = {
    events: [
      {
        title: "Mental ariphmetics",
        start: "2024-06-01",
        schedule: "13:00-13:45",
        subject: "Ментальная арифметика",
        time_start: "13:00",
        duration: "45",
        available: true,
        group: 'math',
      },
      {
        title: "Mental ariphmetics",
        start: "2024-06-02",
        schedule: "13:00-13:45",
        subject: "Ментальная арифметика",
        time_start: "13:00",
        duration: "45",
        available: true,
        group: 'math',
      },
      {
        title: "Mental ariphmetics",
        start: "2024-06-16",
        schedule: "13:00-13:45",
        subject: "Ментальная арифметика",
        time_start: "13:00",
        duration: "45",
        available: true,
        group: 'math',
      },
      {
        title: "Mental ariphmetics",
        start: "2024-06-17",
        schedule: "13:00-13:45",
        subject: "Ментальная арифметика",
        time_start: "13:00",
        duration: "45",
        available: true,
        group: 'math',
      },
      {
        title: "Mental ariphmetics",
        start: "2024-06-07",
        schedule: "13:00-13:45",
        subject: "Ментальная арифметика",
        time_start: "13:00",
        duration: "45",
        available: true,
        group: 'math',
      },
      {
        title: "Robotics",
        start: "2024-06-01",
        schedule: "14:00-14:45",
        subject: "Робототехника",
        time_start: "14:00",
        duration: "45",
        available: true,
        group: 'engineer',
      },
      {
        title: "Robotics",
        start: "2024-06-02",
        schedule: "14:00-14:45",
        subject: "Робототехника",
        time_start: "14:00",
        duration: "45",
        available: true,
        group: 'engineer',
      },
      {
        title: "Robotics",
        start: "2024-06-30",
        schedule: "14:00-14:45",
        subject: "Робототехника",
        time_start: "14:00",
        duration: "45",
        available: true,
        group: 'engineer',
      },
      // etc...
    ],
};
  
export const eventsInitial = {
    events: [
      {
        title: "Mental ariphmetics",
        start: "2024-06-01",
        schedule: "13:00-13:45",
        subject: "Ментальная арифметика",
        time_start: "13:00",
        duration: "45",
        available: true,
        group: 'math',
      },
      {
        title: "Mental ariphmetics",
        start: "2024-06-02",
        schedule: "13:00-13:45",
        subject: "Ментальная арифметика",
        time_start: "13:00",
        duration: "45",
        available: true,
        group: 'math',
      },
      {
        title: "Mental ariphmetics",
        start: "2024-06-16",
        schedule: "13:00-13:45",
        subject: "Ментальная арифметика",
        time_start: "13:00",
        duration: "45",
        available: true,
        group: 'math',
      },
      {
        title: "Mental ariphmetics",
        start: "2024-06-17",
        schedule: "13:00-13:45",
        subject: "Ментальная арифметика",
        time_start: "13:00",
        duration: "45",
        available: true,
        group: 'math',
      },
      {
        title: "Mental ariphmetics",
        start: "2024-06-07",
        schedule: "13:00-13:45",
        subject: "Ментальная арифметика",
        time_start: "13:00",
        duration: "45",
        available: true,
        group: 'math',
      },
      {
        title: "Robotics",
        start: "2024-06-01",
        schedule: "14:00-14:45",
        subject: "Робототехника",
        time_start: "14:00",
        duration: "45",
        available: true,
        group: 'engineer',
      },
      {
        title: "Robotics",
        start: "2024-06-02",
        schedule: "14:00-14:45",
        subject: "Робототехника",
        time_start: "14:00",
        duration: "45",
        available: true,
        group: 'engineer',
      },
      {
        title: "Robotics",
        start: "2024-06-30",
        schedule: "14:00-14:45",
        subject: "Робототехника",
        time_start: "14:00",
        duration: "45",
        available: true,
        group: 'engineer',
      },
      // etc...
    ],
  };